import { Subscriber } from "./subscriber.model"

export class Repository {
    archive_url: String
    archived: boolean
    assignees_url: String
    blobs_url: String
    branches_url: String
    clone_url: String
    collaborators_url: String
    comments_url: String
    commits_url: String
    compare_url: String
    contents_url: String
    contributors_url: String
    created_at: String
    default_branch: String
    deployments_url: String
    description: String
    disabled: boolean
    downloads_url: String
    events_url: String
    fork: boolean
    forks: number
    forks_count: number
    forks_url: String
    full_name: String
    git_commits_url: String
    git_refs_url: String
    git_tags_url: String
    git_url: String
    has_downloads: boolean
    has_issues: boolean
    has_pages: boolean
    has_projects: boolean
    has_wiki: boolean
    homepage: String
    hooks_url: String
    html_url: String
    id: number
    issue_comment_url: String
    issue_events_url: String
    issues_url: String
    keys_url: String
    labels_url: String
    language: String
    languages_url: String
    license: any
    merges_url: String
    milestones_url: String
    mirror_url: String
    name: String
    node_id: String
    notifications_url: String
    open_issues: number
    open_issues_count: number
    owner: Subscriber
    permissions: any
    private: boolean
    pulls_url: String
    pushed_at:String
    releases_url: String
    size: number
    ssh_url: String
    stargazers_count: number
    stargazers_url: String
    statuses_url: String
    subscribers_url: String
    subscription_url: String
    svn_url: String
    tags_url: String
    teams_url: String
    trees_url: String
    updated_at: String
    url: String
    watchers: number
    watchers_count: number
  }